import { async } from '@firebase/util';
import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head'
import Banner from '../components/Banner'
import Component from '../components/Component';
import Footer from '../components/Footer';
import Header from '../components/Header'
import LargeCard from '../components/LargeCard';
import MediumCard from '../components/MediumCard';
import SmallCard from '../components/SmallCard';



export default function Home({exploreData,cardsData,session}) {
  // const {session}=useSession();
  return (
    <div className="">
      <Head>
        <title>SAIF Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header*/}
      <Header />
      <Component />
      {/* banner*/}
      <Banner />
     <main className='max-w-7xl mx-auto p-2 sm:px-16'>
      <section className='pt-6'>
        <h2 className='text-4xl font-semibold pb-5' >Explore Nearby</h2>

        {/* pull server */}
        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            
        {exploreData?.map(({img,distance,location})=>(
          <SmallCard key={img} img={img} distance={distance} location={location} />
        ))}  

        </div>
      
      </section>

      <section>
        <h2 className='text-4xl font-semibold pl-4 py-8'>Live Anywhere</h2>
        <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 ml-3'>

        {cardsData?.map(({img,title}) => (
          <MediumCard key={img} img={img} title={title} />
        ))}
           
        </div>
       
      </section>
      <LargeCard 
      img="https://links.papareact.com/4cj"
      title='The Greatest Outdoors'
      description='Wishlists curated by Saifur Rahman'
      buttonText='Get Inspired'
      />
       
     </main>
     <Footer />

      {/* */}
      {/* */}
    </div>
  )
}
// https://links.papareact.com/pyp isko change ker raha custom me

export async function getServerSideProps(){
  const exploreData =await fetch('https://jsonkeeper.com/b/WM5B').then(
    (res) => res.json()
  );
  // const session =await getSession();
  const cardsData = await fetch("https:/links.papareact.com/zp1" || "https://links.papareact.com/pyp").then(res => res.json());
   
   return{
     props:{
       exploreData,
       cardsData,
      //  session

     }
     
   }

}
// export async function getServerSideProps(context){
  
//   return{
//     props:{
//         session,
//     },
//   };
// }
